// DFPT input file generation.
//
// Reads a pw.x SCF input file and writes the four QE input files needed for a
// complete DFPT phonon calculation:
//
//   ph.in          – ph.x: compute dynamical matrices on a q-mesh (DFPT)
//   q2r.in         – q2r.x: Fourier-transform D(q) → real-space IFCs Φ(R)
//   matdyn_dos.in  – matdyn.x: compute phonon DOS from Φ(R)
//   matdyn_band.in – matdyn.x: compute phonon band structure from Φ(R)
//
// Workflow after generating inputs:
//   pw.x        -in scf.in                      (already done)
//   ph.x        -in ph.in        > ph.out        (DFPT)
//   q2r.x            < q2r.in   > q2r.out        (real-space IFCs)
//   matdyn.x         < matdyn_dos.in             (DOS)
//   matdyn.x         < matdyn_band.in            (dispersion)
//   qepp phonon -post <prefix>                   (plot + HA)

#include "qe/dfpt.hpp"
#include "qe/utils.hpp"

#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace qe {

namespace {

// Create directory if it does not exist.
void ensure_dir(const std::string& dir) {
    if (!dir.empty() && dir != ".")
        std::filesystem::create_directories(dir);
}

// Join directory and filename.
std::string join_path(const std::string& dir, const std::string& file) {
    if (dir.empty() || dir == ".") return file;
    return dir + "/" + file;
}

}  // anonymous namespace

// ── generate_phonon_inputs ────────────────────────────────────────────────────

std::vector<std::string> generate_phonon_inputs(
    const std::string& scfInputPath,
    const std::string& outDir,
    const DfptOptions& opts,
    bool verbose)
{
    const auto lines = load_lines(scfInputPath);

    // Extract prefix and outdir from SCF input
    std::string prefix = extract_quoted_assignment(lines, "prefix");
    std::string qeOutdir = extract_quoted_assignment(lines, "outdir");
    if (prefix.empty())  prefix   = stem_from_path(scfInputPath);
    if (qeOutdir.empty()) qeOutdir = "./tmp";

    // Extract nat for validation / informational messages
    int nat = 0;
    for (const auto& l : lines) {
        const std::string lower = to_lower(trim(l));
        if (lower.rfind("nat", 0) == 0 || lower.find(" nat ") != std::string::npos
            || lower.find(",nat") != std::string::npos
            || lower.find("nat=") != std::string::npos) {
            // "nat = N,"
            const auto pos = l.find('=');
            if (pos != std::string::npos) {
                try { nat = std::stoi(l.substr(pos + 1)); } catch (...) {}
                if (nat > 0) break;
            }
        }
    }

    ensure_dir(outDir);

    const std::string phPath  = join_path(outDir, "ph.in");
    const std::string q2rPath = join_path(outDir, "q2r.in");
    const std::string mdDos   = join_path(outDir, "matdyn_dos.in");
    const std::string mdBand  = join_path(outDir, "matdyn_band.in");

    // ── ph.in ─────────────────────────────────────────────────────────────
    // ph.x performs the DFPT phonon calculation on a Monkhorst-Pack q-mesh.
    // ldisp=.true. computes the full BZ; fildyn is the stem for dynamical-
    // matrix files (QE appends 1, 2, ... for each irreducible q-point).
    {
        std::ofstream out(phPath);
        if (!out) throw std::runtime_error("Cannot create: " + phPath);

        out << "! DFPT phonon calculation — generated by qepp phonon -pre\n";
        out << "! Run: mpirun ph.x -in ph.in > ph.out\n";
        out << "!\n";
        out << "! After ph.x completes, run q2r.in, then matdyn_dos.in and matdyn_band.in.\n";
        if (nat > 0)
            out << "! Crystal has nat=" << nat << " atoms.\n";
        out << " Phonon calculation\n";
        out << " &inputph\n";
        out << "   prefix    = '" << prefix   << "',\n";
        out << "   outdir    = '" << qeOutdir  << "',\n";
        out << "   tr2_ph    = " << std::scientific << std::setprecision(1)
            << opts.tr2_ph << ",\n";
        out << "   ldisp     = .true.,\n";
        out << "   nq1       = " << opts.nq1 << ",\n";
        out << "   nq2       = " << opts.nq2 << ",\n";
        out << "   nq3       = " << opts.nq3 << ",\n";
        if (opts.epsil)
            out << "   epsil     = .true.,\n";
        out << "   fildyn    = '" << prefix << ".dyn',\n";
        out << " /\n";
    }

    // ── q2r.in ────────────────────────────────────────────────────────────
    // q2r.x Fourier-transforms the dynamical matrices D(q) computed by ph.x
    // to real-space interatomic force constants Φ(R) stored in prefix.fc.
    // zasr enforces the acoustic sum rule.
    {
        std::ofstream out(q2rPath);
        if (!out) throw std::runtime_error("Cannot create: " + q2rPath);

        out << "! q2r.x: convert dynamical matrices D(q) to real-space IFCs\n";
        out << "! Run: q2r.x < q2r.in > q2r.out\n";
        out << " &input\n";
        out << "   fildyn = '" << prefix << ".dyn',\n";
        out << "   zasr   = '" << opts.asr << "',\n";
        out << "   flfrc  = '" << prefix << ".fc',\n";
        out << " /\n";
    }

    // ── matdyn_dos.in ─────────────────────────────────────────────────────
    // matdyn.x interpolates Φ(R) to a fine q-mesh and computes the DOS.
    // deltaE sets the frequency resolution in cm⁻¹; nk1/2/3 the DOS q-mesh.
    {
        std::ofstream out(mdDos);
        if (!out) throw std::runtime_error("Cannot create: " + mdDos);

        out << "! matdyn.x: compute phonon DOS\n";
        out << "! Run: matdyn.x < matdyn_dos.in > matdyn_dos.out\n";
        out << "! Output: " << prefix << ".phonon.dos\n";
        out << " &input\n";
        out << "   asr    = '" << opts.asr << "',\n";
        out << "   flfrc  = '" << prefix << ".fc',\n";
        out << "   dos    = .true.,\n";
        out << "   fldos  = '" << prefix << ".phonon.dos',\n";
        out << "   flfrq  = '" << prefix << ".phonon.freq',\n";
        out << "   nk1    = " << opts.nqDos1 << ",\n";
        out << "   nk2    = " << opts.nqDos2 << ",\n";
        out << "   nk3    = " << opts.nqDos3 << ",\n";
        out << "   deltaE = 1.0,\n";
        out << " /\n";
    }

    // ── matdyn_band.in ────────────────────────────────────────────────────
    // matdyn.x interpolates Φ(R) along a high-symmetry path for the band plot.
    // q_in_band_form=.true. lets the user specify (q-start, q-end, npoints)
    // triples.  The default path below is Γ→X→M→Γ→R (cubic / FCC placeholder).
    // Replace with the correct path for your crystal system.
    {
        std::ofstream out(mdBand);
        if (!out) throw std::runtime_error("Cannot create: " + mdBand);

        out << "! matdyn.x: compute phonon band structure\n";
        out << "! Run: matdyn.x < matdyn_band.in > matdyn_band.out\n";
        out << "! Output: " << prefix << ".phonon_band.freq\n";
        out << "! NOTE: Replace the q-path below with the correct one for your\n";
        out << "!       crystal (see qepp kpath -pre for k-path generation).\n";
        out << "!       Units: crystal coordinates (fractions of rec. lat. vectors)\n";
        out << " &input\n";
        out << "   asr            = '" << opts.asr << "',\n";
        out << "   flfrc          = '" << prefix << ".fc',\n";
        out << "   flfrq          = '" << prefix << ".phonon_band.freq',\n";
        out << "   q_in_band_form = .true.,\n";
        out << " /\n";
        out << "! Number of path segments (including the final endpoint)\n";
        out << "  5\n";
        out << "  0.000  0.000  0.000   40  ! Gamma\n";
        out << "  0.500  0.000  0.500   40  ! X\n";
        out << "  0.500  0.250  0.750   20  ! W\n";
        out << "  0.500  0.500  0.500   40  ! L\n";
        out << "  0.000  0.000  0.000    1  ! Gamma (endpoint)\n";
    }

    const std::vector<std::string> generated = {phPath, q2rPath, mdDos, mdBand};

    if (verbose) {
        std::cout << "Generated DFPT input files for prefix = '" << prefix << "':\n";
        for (const auto& p : generated)
            std::cout << "  " << p << "\n";
        std::cout << "\nWorkflow:\n";
        std::cout << "  1. mpirun ph.x    -in " << phPath  << " > ph.out\n";
        std::cout << "  2. q2r.x               < " << q2rPath << " > q2r.out\n";
        std::cout << "  3. matdyn.x            < " << mdDos   << " > matdyn_dos.out\n";
        std::cout << "  4. matdyn.x            < " << mdBand  << " > matdyn_band.out\n";
        std::cout << "  5. qepp phonon -post " << prefix << "\n";
    }

    return generated;
}

}  // namespace qe
