#include "qe/help.hpp"

#include <iostream>

void print_help(const char* prog) {
    std::cout <<
        "qepp — Quantum ESPRESSO post-processor and input generator\n"
        "\n"
        "USAGE\n"
        "  " << prog << " <command> -pre  [arguments]   (pre-processing)\n"
        "  " << prog << " <command> -run  [arguments]   (workflow execution)\n"
        "  " << prog << " <command> -post [arguments]   (post-processing)\n"
        "  " << prog << " help [command] [-pre|-run|-post]\n"
        "\n"
        "COMMANDS\n"
        "  cif     -pre   Generate a QE SCF input from a CIF file\n"
        "  dos     -post  Plot density of states from a QE dos.x output\n"
        "  band    -pre   Generate QE band-structure inputs (pw.x + bands.x) from a CIF\n"
        "  band    -post  Plot band structure from a QE bands.x output\n"
        "  kpath   -pre   Suggest a high-symmetry k-path from a CIF file\n"
        "  elastic -pre   Generate deformed SCF inputs for elastic constants\n"
        "  elastic -run   Run equilibrium + strained SCF jobs for elastic constants\n"
        "  elastic -post  Collect energies and compute elastic constants\n"
        "  charge  -pre   Generate pp.x inputs for charge density / charge diff / ELF\n"
        "  charge  -post  Plot volumetric data from a cube file\n"
        "  mag     -post  Tabulate per-atom magnetic moments from a QE pw.x output\n"
        "  stm     -pre   Generate pp.x input for STM simulation (ILDOS, Tersoff-Hamann)\n"
        "  stm     -post  Plot 2D constant-height STM map from a cube file\n"
        "  bader   -post  Tabulate per-atom Bader charges from ACF.dat\n"
        "  conv    -pre   Generate SCF inputs for ecutwfc or k-mesh convergence testing\n"
        "  conv    -post  Parse energies and plot convergence curve\n"
        "  struct  -post  Print lattice parameters, cell vectors, and atomic positions\n"
        "  parse   -post  Extract energy, Fermi level, forces, pressure, timing from QE output\n"
        "  qha     -pre   Generate scaled SCF inputs for quasi-harmonic approximation\n"
        "  qha     -post  Compute QHA thermal properties from phonopy yamls + DFT energies\n"
        "  qha_elastic -pre   Generate volume-scaled elastic + DFPT inputs\n"
        "  qha_elastic -run   Run the generated QHA elastic workflow\n"
        "  qha_elastic -post  Compute temperature-dependent elastic constants\n"
        "  phonon  -pre   Generate DFPT phonon inputs (ph.x, q2r.x, matdyn.x)\n"
        "  phonon  -post  Post-process DFPT matdyn.x output (DOS, band, HA)\n"
        "  phonon  -dos   Plot phonon DOS (phonopy or matdyn.x format)\n"
        "  phonon  -band  Plot phonon band structure (phonopy or matdyn.x format)\n"
        "  phonon  -ha    Harmonic approximation thermodynamics (phonopy or matdyn.x)\n"
        "\n"
        "Run '" << prog << " help <command>' or '" << prog << " <command> --help' for details.\n";
}

void print_help_command(const char* prog, const std::string& cmd,
                        const std::string& sub) {
    // ── cif ──────────────────────────────────────────────────────────────────
    if (cmd == "cif") {
        std::cout <<
            "DESCRIPTION\n"
            "  Reads a CIF (Crystallographic Information File) and generates a ready-to-run\n"
            "  Quantum ESPRESSO pw.x SCF input. The cell vectors, atomic positions, and species\n"
            "  are taken directly from the CIF. A Monkhorst-Pack k-mesh is built automatically\n"
            "  from the requested k-point spacing. Pseudopotential filenames are left as\n"
            "  placeholders that you fill in before running pw.x.\n"
            "\n"
            "USAGE\n"
            "  " << prog << " cif -pre <input.cif> <kspacing> [output.in] [ecutwfc] [ecutrho]\n"
            "\n"
            "ARGUMENTS\n"
            "  input.cif    CIF structure file\n"
            "  kspacing     K-point spacing in 1/Angstrom (e.g. 0.15); smaller = denser mesh\n"
            "  output.in    Output QE input file (default: <stem>.scf.in)\n"
            "  ecutwfc      Plane-wave cutoff in Ry (default: 50)\n"
            "  ecutrho      Charge density cutoff in Ry (default: 8*ecutwfc)\n"
            "\n"
            "EXAMPLES\n"
            "  " << prog << " cif -pre si.cif 0.15\n"
            "  " << prog << " cif -pre al.cif 0.20 al.scf.in 40 320\n";
    }
    // ── dos ──────────────────────────────────────────────────────────────────
    else if (cmd == "dos") {
        std::cout <<
            "DESCRIPTION\n"
            "  Reads the DOS table produced by QE dos.x and generates PNG plots of the\n"
            "  density of states using Matplot++. The energy axis is shifted so that the\n"
            "  Fermi level sits at 0 eV. The Fermi energy can be supplied directly as a number\n"
            "  or extracted automatically from a QE SCF/NSCF output file.\n"
            "\n"
            "  If projwfc.x partial-DOS files (<prefix>.pdos_atm#*) are found in the same\n"
            "  directory, two additional plots are generated automatically:\n"
            "    <prefix>.pdos_elem.png  — elemental contributions (one curve per element)\n"
            "    <prefix>.pdos_orb.png   — orbital contributions summed (s, p, d, f)\n"
            "\n"
            "  If d-orbital PDOS is available, a descriptor report is also written:\n"
            "    <prefix>.dband.txt\n"
            "  containing d-band center and d-band width from both methodologies:\n"
            "    old: occupied states only (E <= E_F)\n"
            "    new: full d-band (all sampled states)\n"
            "\n"
            "USAGE\n"
            "  " << prog << " dos -post <qe_dos_file> [fermi_eV|qe_output.out] [output_prefix]\n"
            "\n"
            "ARGUMENTS\n"
            "  qe_dos_file      Output of QE dos.x (e.g. si.dos)\n"
            "  fermi_eV         Fermi energy in eV, or path to QE scf/nscf output to extract it\n"
            "  output_prefix    Prefix for generated plot files (default: stem of dos file)\n"
            "\n"
            "EXAMPLES\n"
            "  " << prog << " dos -post si.dos 6.341\n"
            "  " << prog << " dos -post si.dos si.scf.out\n"
            "  " << prog << " dos -post si.dos si.scf.out si_plot\n"
            "\n"
            "NOTE\n"
            "  For PDOS, run 'projwfc.x' after 'dos.x' using the same prefix and outdir.\n"
            "  projwfc.x will create files like: <prefix>.pdos_atm#1(Si)_wfc#1(s)\n";
    }
    // ── band ─────────────────────────────────────────────────────────────────
    else if (cmd == "band") {
        if (sub == "-pre") {
            std::cout <<
                "DESCRIPTION\n"
                "  Automates the setup of a QE band-structure calculation. Given a CIF file\n"
                "  and an existing SCF input, it determines the crystal symmetry, selects the\n"
                "  standard high-symmetry k-path for that Bravais lattice, and writes two\n"
                "  ready-to-run input files: one for pw.x (non-SCF bands run) and one for\n"
                "  bands.x (post-processing). All settings (prefix, pseudo_dir, outdir,\n"
                "  cutoffs) are inherited from the SCF input.\n"
                "\n"
                "USAGE\n"
                "  " << prog << " band -pre <input.cif> <scf_input.in> [bands_pw.in] [bands_pp.in] [pts] [nbnd]\n"
                "\n"
                "ARGUMENTS\n"
                "  input.cif          CIF structure file (used to determine the k-path)\n"
                "  scf_input.in       Existing SCF input (prefix, pseudo_dir, outdir reused)\n"
                "  bands_pw.in        Output pw.x bands input (default: <stem>.bands.in)\n"
                "  bands_pp.in        Output bands.x input (default: <stem>.bands_pp.in)\n"
                "  pts                K-points per segment (default: 20)\n"
                "  nbnd               Total number of bands including empty bands\n"
                "                     (default: 0 = let QE decide; set e.g. 2x occupied to\n"
                "                     see conduction bands and the band gap)\n"
                "\n"
                "EXAMPLES\n"
                "  " << prog << " band -pre si.cif si.scf.in\n"
                "  " << prog << " band -pre si.cif si.scf.in si.bands.in si.bands_pp.in 40 8\n";
        } else if (sub == "-post") {
            std::cout <<
                "DESCRIPTION\n"
                "  Reads the band-structure data produced by QE bands.x (the .dat.gnu file)\n"
                "  and generates a PNG plot of the electronic band structure using Matplot++.\n"
                "  High-symmetry k-point positions are detected automatically from\n"
                "  discontinuities in the k-path; labels can optionally be supplied on the\n"
                "  command line. The energy axis is shifted to place the Fermi level at 0 eV.\n"
                "\n"
                "USAGE\n"
                "  " << prog << " band -post <qe_band_file> [fermi_eV|qe_output.out] [output_prefix] [labels]\n"
                "\n"
                "ARGUMENTS\n"
                "  qe_band_file     Output of QE bands.x (e.g. si.bands.dat.gnu)\n"
                "  fermi_eV         Fermi energy in eV, or path to QE scf/nscf output\n"
                "  output_prefix    Prefix for generated plot files (default: stem of band file)\n"
                "  labels           Comma-separated high-symmetry labels, e.g. L,G,X,W,K,G\n"
                "\n"
                "EXAMPLES\n"
                "  " << prog << " band -post si.bands.dat.gnu 6.341\n"
                "  " << prog << " band -post si.bands.dat.gnu si.scf.out si_bands L,G,X,W,K,G\n";
        } else if (sub == "-fat") {
            std::cout <<
                "DESCRIPTION\n"
                "  Plots a fat (projected) band structure. Thin gray lines show all bands;\n"
                "  colored scatter bubbles (area proportional to projection weight) show\n"
                "  the contribution of selected elements, atoms, or orbitals, computed from\n"
                "  the atomic_proj.xml produced by QE projwfc.x.\n"
                "\n"
                "  When band -pre is run it also writes a projwfc.x input file alongside\n"
                "  the bands_pp.in. After running pw.x (bands) and projwfc.x, call -fat.\n"
                "\n"
                "USAGE\n"
                "  " << prog << " band -fat <bands.dat.gnu> <atomic_proj.xml> [outprefix] [fermi_eV|qe_output.out] [filter ...]\n"
                "\n"
                "ARGUMENTS\n"
                "  bands.dat.gnu     Band-structure data file from bands.x (the .gnu file)\n"
                "  atomic_proj.xml   Projection data from projwfc.x (in <outdir>/<prefix>.save/)\n"
                "  outprefix         Output prefix for PNG files (default: stem of .gnu file)\n"
                "  fermi_eV          Fermi energy in eV, OR path to QE scf/nscf output\n"
                "  filter            One or more of (all combinable):\n"
                "    element=Si,Fe     filter by element name\n"
                "    atom=1,3          filter by 1-based atom index\n"
                "    orbital=s,p,d,f   filter by orbital type (s/p/d/f)\n"
                "\n"
                "GROUPING\n"
                "  element + orbital  → one PNG per (element, orbital) pair\n"
                "  element only       → one PNG per element\n"
                "  atom + orbital     → one PNG per (atom, orbital) pair\n"
                "  atom only          → one PNG per atom\n"
                "  orbital only       → one PNG per orbital, summed over all atoms\n"
                "  none               → auto: one PNG per distinct element\n"
                "  If >1 group, an additional combined PNG is produced.\n"
                "\n"
                "OUTPUT\n"
                "  <outprefix>.fatband_<group>.png  — one PNG per group\n"
                "  <outprefix>.fatband_combined.png — all groups overlaid (if >1 group)\n"
                "\n"
                "EXAMPLES\n"
                "  " << prog << " band -fat si.bands.dat.gnu tmp/si.save/atomic_proj.xml si 6.204\n"
                "  " << prog << " band -fat si.bands.dat.gnu tmp/si.save/atomic_proj.xml si 6.204 element=Si\n"
                "  " << prog << " band -fat si.bands.dat.gnu tmp/si.save/atomic_proj.xml si 6.204 orbital=s,p\n"
                "  " << prog << " band -fat si.bands.dat.gnu tmp/si.save/atomic_proj.xml si 6.204 element=Si orbital=s,p\n"
                "  " << prog << " band -fat bi2se3.bands.dat.gnu tmp/bi2se3.save/atomic_proj.xml bi2se3 12.5 element=Bi,Se\n"
                "  " << prog << " band -fat bi2se3.bands.dat.gnu tmp/bi2se3.save/atomic_proj.xml bi2se3 12.5 atom=1,2\n";
        } else {
            std::cout <<
                "USAGE\n"
                "  " << prog << " band -pre  <input.cif> <scf_input.in> [bands_pw.in] [bands_pp.in] [pts]\n"
                "  " << prog << " band -post <qe_band_file> [fermi_eV|qe_output.out] [output_prefix] [labels]\n"
                "  " << prog << " band -fat  <bands.dat.gnu> <atomic_proj.xml> [outprefix] [fermi_eV|out] [filter]\n"
                "\n"
                "Run '" << prog << " band -pre --help' or '" << prog << " band -post --help' or\n"
                "'" << prog << " band -fat --help' for details.\n";
        }
    }
    // ── kpath ─────────────────────────────────────────────────────────────────
    else if (cmd == "kpath") {
        std::cout <<
            "DESCRIPTION\n"
            "  Reads a CIF file, identifies the Bravais lattice and crystal family via spglib\n"
            "  (or ibrav fallback), and prints the standard high-symmetry k-path as a\n"
            "  K_POINTS crystal_b block ready to paste into a QE input file. Optionally writes\n"
            "  the block to a file.\n"
            "\n"
            "USAGE\n"
            "  " << prog << " kpath -pre <input.cif> [pts_per_segment] [output.kpath]\n"
            "\n"
            "ARGUMENTS\n"
            "  input.cif        CIF structure file\n"
            "  pts_per_segment  Points per k-path segment (default: 20)\n"
            "  output.kpath     Write K_POINTS block to this file (default: stdout only)\n"
            "\n"
            "EXAMPLES\n"
            "  " << prog << " kpath -pre si.cif\n"
            "  " << prog << " kpath -pre si.cif 40 si.kpath\n";
    }
    // ── elastic ───────────────────────────────────────────────────────────────
    else if (cmd == "elastic") {
        if (sub == "-pre") {
            std::cout <<
                "DESCRIPTION\n"
                "  Pre-processing step for computing elastic constants via the energy-strain\n"
                "  method. Reads an equilibrium QE SCF input, detects the crystal symmetry,\n"
                "  and generates a set of strained pw.x input files covering all\n"
                "  symmetry-independent strain patterns. Each pattern directory contains\n"
                "  inputs at evenly-spaced strain amplitudes from -max_delta to +max_delta.\n"
                "  After running all pw.x jobs, use 'elastic -post' to extract constants.\n"
                "\n"
                "USAGE\n"
                "  " << prog << " elastic -pre <scf_template.in> <outdir> [ndeltas] [max_delta]\n"
                "\n"
                "ARGUMENTS\n"
                "  scf_template.in  QE SCF input for the equilibrium structure\n"
                "                   (ibrav=0 with CELL_PARAMETERS, or ibrav+celldm)\n"
                "  outdir           Root directory where strain subdirectories are created\n"
                "  ndeltas          Number of strain points per pattern, odd (default: 7)\n"
                "  max_delta        Maximum strain magnitude, e.g. 0.04 = 4% (default: 0.04)\n"
                "\n"
                "OUTPUT STRUCTURE\n"
                "  outdir/\n"
                "    e1/   p0.0400/si.in  m0.0400/si.in  ...\n"
                "    e1e2/ p0.0400/si.in  ...\n"
                "    e4/   ...\n"
                "\n"
                "EXAMPLES\n"
                "  " << prog << " elastic -pre si.scf.in elastic_si\n"
                "  " << prog << " elastic -pre si.scf.in elastic_si 9 0.03\n"
                "\n"
                "NOTE\n"
                "  Crystal symmetry is detected automatically (spglib if available, else ibrav).\n"
                "  Only the symmetry-independent strain patterns are generated.\n";
        } else if (sub == "-run") {
            std::cout <<
                "DESCRIPTION\n"
                "  Run the 0 K elastic workflow created by 'elastic -pre'. This first runs\n"
                "  the equilibrium SCF template as qe.out, then runs every strained pw.x job\n"
                "  under <outdir>. Existing outputs containing JOB DONE are skipped.\n"
                "  If you pass only one directory, qepp auto-detects folder names and\n"
                "  tries to locate the matching template input automatically.\n"
                "\n"
                "USAGE\n"
                "  " << prog << " elastic -run <scf_template.in> <outdir>\n"
                "  " << prog << " elastic -run <outdir_or_volume_dir>\n"
                "                     [--np N] [--ni N] [--nk N] [--nb N] [--nt N] [--nd N]\n"
                "\n"
                "OPTIONS\n"
                "  --np N   MPI ranks passed to mpirun (default: 1)\n"
                "  --ni N   QE image groups   (-ni)\n"
                "  --nk N   QE k-point pools  (-nk)\n"
                "  --nb N   QE band groups    (-nb)\n"
                "  --nt N   QE task groups    (-nt)\n"
                "  --nd N   QE diagonalization groups (-nd)\n"
                "\n"
                "EXAMPLES\n"
                "  " << prog << " elastic -run si.scf.in elastic_si --np 16 --nk 4\n"
                "  " << prog << " elastic -run tests/al_qha_el_litfix_new/v01 --np 16 --nk 4\n";
        } else if (sub == "-post") {
            std::cout <<
                "DESCRIPTION\n"
                "  Post-processing step for elastic constants. Scans the output directories\n"
                "  created by 'elastic -pre', extracts the DFT total energies from each pw.x\n"
                "  output, fits a quadratic E(delta) polynomial per strain pattern, and\n"
                "  assembles the full 6x6 stiffness matrix (Cij, in GPa) using the appropriate\n"
                "  crystal-symmetry relations. Derived mechanical properties (bulk modulus K,\n"
                "  shear modulus G, Young's modulus E, Poisson's ratio nu) are reported via\n"
                "  the Voigt-Reuss-Hill average. A Born stability check is also performed.\n"
                "\n"
                "USAGE\n"
                "  " << prog << " elastic -post <scf_template.in> <outdir>\n"
                "  " << prog << " elastic -post <outdir_or_volume_dir>\n"
                "\n"
                "ARGUMENTS\n"
                "  scf_template.in  Same template used with 'elastic -pre' (provides cell)\n"
                "  outdir           Same root directory used with 'elastic -pre'\n"
                "\n"
                "OUTPUT\n"
                "  Full 6x6 stiffness matrix (GPa), independent elastic constants, bulk\n"
                "  modulus, shear modulus, Young's modulus, Poisson's ratio, stability check.\n"
                "  Saves a report to outdir/elastic_results.txt\n"
                "\n"
                "EXAMPLES\n"
                "  " << prog << " elastic -post si.scf.in elastic_si\n"
                "  " << prog << " elastic -post tests/al_qha_el_litfix_new/v01\n";
        } else {
            std::cout <<
                "USAGE\n"
                "  " << prog << " elastic -pre  <scf_template.in> <outdir> [ndeltas] [max_delta]\n"
                "  " << prog << " elastic -run  <scf_template.in> <outdir> [--np N] [--ni N] [--nk N] [--nb N] [--nt N] [--nd N]\n"
                "  " << prog << " elastic -run  <outdir_or_volume_dir> [--np N] [--ni N] [--nk N] [--nb N] [--nt N] [--nd N]\n"
                "  " << prog << " elastic -post <scf_template.in> <outdir>\n"
                "  " << prog << " elastic -post <outdir_or_volume_dir>\n"
                "\n"
                "WORKFLOW\n"
                "  1. " << prog << " elastic -pre  si.scf.in elastic_si\n"
                "  2. " << prog << " elastic -run  si.scf.in elastic_si --np 16 --nk 4\n"
                "  3. " << prog << " elastic -post si.scf.in elastic_si\n"
                "\n"
                "Run '" << prog << " elastic -pre --help', '" << prog << " elastic -run --help', or '" << prog << " elastic -post --help' for details.\n";
        }
    }
    else if (cmd == "charge") {
        if (sub == "-pre") {
            std::cout <<
                "DESCRIPTION\n"
                "  Generates three pp.x input files for QE post-processing:\n"
                "    charge density         (plot_num=0)\n"
                "    charge-density difference (plot_num=6)\n"
                "    electron localisation function, ELF (plot_num=8)\n"
                "\n"
                "USAGE\n"
                "  " << prog << " charge -pre <scf.in> [outdir]\n"
                "\n"
                "ARGUMENTS\n"
                "  scf.in    QE SCF input file (used to extract prefix and outdir)\n"
                "  outdir    Directory where pp.x inputs are written (default: <stem>_charge/)\n"
                "\n"
                "OUTPUT\n"
                "  <outdir>/<prefix>.charge.pp.in\n"
                "  <outdir>/<prefix>.charge_diff.pp.in\n"
                "  <outdir>/<prefix>.elf.pp.in\n"
                "\n"
                "EXAMPLES\n"
                "  " << prog << " charge -pre si.scf.in si_charge\n";
        } else if (sub == "-post") {
            std::cout <<
                "DESCRIPTION\n"
                "  Reads a Gaussian cube file produced by QE pp.x and generates:\n"
                "    <outprefix>.slice.png  — three orthogonal midplane heatmaps (XY, XZ, YZ)\n"
                "    <outprefix>.3d.png     — 3-D scatter of high-value points (isosurface proxy)\n"
                "\n"
                "USAGE\n"
                "  " << prog << " charge -post <cube_file> [outprefix] [quantity]\n"
                "\n"
                "ARGUMENTS\n"
                "  cube_file   Cube file produced by pp.x (output_format=6)\n"
                "  outprefix   Output filename prefix (default: stem of cube_file)\n"
                "  quantity    One of: charge (default), charge_diff, elf\n"
                "              Affects colour map and thresholding\n"
                "\n"
                "EXAMPLES\n"
                "  " << prog << " charge -post si.charge.cube si_charge charge\n"
                "  " << prog << " charge -post si.charge_diff.cube si_charge_diff charge_diff\n"
                "  " << prog << " charge -post si.elf.cube si_elf elf\n";
        } else {
            std::cout <<
                "USAGE\n"
                "  " << prog << " charge -pre  <scf.in> [outdir]\n"
                "  " << prog << " charge -post <cube_file> [outprefix] [quantity]\n"
                "\n"
                "WORKFLOW\n"
                "  1. " << prog << " charge -pre si.scf.in si_charge\n"
                "  2. cd si_charge && pp.x < si.charge.pp.in > si.charge.pp.out\n"
                "  3. " << prog << " charge -post si.charge.cube si_charge charge\n"
                "\n"
                "Run '" << prog << " charge -pre --help' or '" << prog << " charge -post --help' for details.\n";
        }
    }
    else if (cmd == "mag") {
        std::cout <<
            "DESCRIPTION\n"
            "  Parses a QE pw.x SCF output and prints a per-atom table of magnetic\n"
            "  moments. Supports collinear (nspin=2) and non-collinear\n"
            "  (noncolin=.true.) calculations. Always reports the converged (final\n"
            "  iteration) values. Non-collinear output includes Sx, Sy, Sz components.\n"
            "\n"
            "USAGE\n"
            "  " << prog << " mag -post <qe_output.out> [output_prefix]\n"
            "\n"
            "ARGUMENTS\n"
            "  qe_output.out   pw.x SCF output file\n"
            "  output_prefix   Prefix for <prefix>.mag.txt (default: stem of output file)\n"
            "\n"
            "EXAMPLES\n"
            "  " << prog << " mag -post fe.scf.out\n"
            "  " << prog << " mag -post fe3o4.scf.out fe3o4_mag\n";
    }
    else if (cmd == "stm") {
        if (sub == "-pre") {
            std::cout <<
                "DESCRIPTION\n"
                "  Generates a pp.x input file for STM simulation using the\n"
                "  Tersoff-Hamann approximation (ILDOS, plot_num=5). The energy\n"
                "  window around E_F is set by the bias voltage: positive bias probes\n"
                "  empty states [0, bias], negative bias probes filled states [bias, 0].\n"
                "\n"
                "USAGE\n"
                "  " << prog << " stm -pre <scf.in> [bias_eV] [outdir]\n"
                "\n"
                "ARGUMENTS\n"
                "  scf.in     QE SCF input (used to extract prefix and outdir)\n"
                "  bias_eV    Bias voltage in eV (default: 1.0; positive = empty states)\n"
                "  outdir     Output directory (default: <stem>_stm/)\n"
                "\n"
                "EXAMPLES\n"
                "  " << prog << " stm -pre si.scf.in\n"
                "  " << prog << " stm -pre si.scf.in 0.5 si_stm\n";
        } else if (sub == "-post") {
            std::cout <<
                "DESCRIPTION\n"
                "  Reads the Gaussian cube file produced by pp.x (plot_num=5) and\n"
                "  generates a 2D constant-height XY map PNG using a hot colormap.\n"
                "  The tip height can be specified in Angstrom above the cube origin,\n"
                "  or defaults to the midplane z-index.\n"
                "\n"
                "USAGE\n"
                "  " << prog << " stm -post <stm.cube> [output_prefix] [height_ang]\n"
                "\n"
                "ARGUMENTS\n"
                "  stm.cube       Cube file from pp.x STM run\n"
                "  output_prefix  Output prefix for PNG (default: stem of cube file)\n"
                "  height_ang     Tip height in Ang above cube origin (-1 = midplane)\n"
                "\n"
                "EXAMPLES\n"
                "  " << prog << " stm -post si.stm.cube\n"
                "  " << prog << " stm -post si.stm.cube si_stm 12.5\n";
        } else {
            std::cout <<
                "USAGE\n"
                "  " << prog << " stm -pre  <scf.in> [bias_eV] [outdir]\n"
                "  " << prog << " stm -post <stm.cube> [output_prefix] [height_ang]\n"
                "\n"
                "WORKFLOW\n"
                "  1. " << prog << " stm -pre si.scf.in 1.0 si_stm\n"
                "  2. cd si_stm && pp.x < si.stm.pp.in > si.stm.pp.out\n"
                "  3. " << prog << " stm -post si.stm.cube si_stm\n"
                "\n"
                "Run '" << prog << " stm -pre --help' or '" << prog << " stm -post --help' for details.\n";
        }
    }
    else if (cmd == "bader") {
        std::cout <<
            "DESCRIPTION\n"
            "  Reads ACF.dat produced by Henkelman's bader program and prints a\n"
            "  per-atom table of Bader charges and Bader volumes. If an SCF input\n"
            "  file is provided, element labels are read from ATOMIC_POSITIONS and\n"
            "  assigned to atoms in ACF.dat order.\n"
            "\n"
            "WORKFLOW\n"
            "  1. qepp charge -pre si.scf.in si_charge\n"
            "  2. pp.x < si_charge/si.charge.pp.in > si_charge/si.charge.pp.out\n"
            "  3. bader si.charge.cube   (Henkelman bader binary)\n"
            "  4. qepp bader -post ACF.dat si.scf.in si_bader\n"
            "\n"
            "USAGE\n"
            "  " << prog << " bader -post <ACF.dat> [scf.in] [output_prefix]\n"
            "\n"
            "ARGUMENTS\n"
            "  ACF.dat        Atomic charge file from Henkelman bader\n"
            "  scf.in         QE SCF input for element labels (optional but recommended)\n"
            "  output_prefix  Prefix for <prefix>.bader.txt (default: stem of ACF.dat)\n"
            "\n"
            "EXAMPLES\n"
            "  " << prog << " bader -post ACF.dat\n"
            "  " << prog << " bader -post ACF.dat si.scf.in si_bader\n";
    }
    // ── conv ─────────────────────────────────────────────────────────────────
    else if (cmd == "conv") {
        if (sub == "-pre") {
            std::cout <<
                "DESCRIPTION\n"
                "  Generates a series of QE pw.x SCF input files varying ecutwfc or k-mesh\n"
                "  spacing. Each run goes into its own subdirectory <outdir>/<param>_<value>/.\n"
                "  After running pw.x in each subdirectory (scf.in -> scf.out), use conv -post\n"
                "  to parse energies and plot the convergence curve.\n"
                "\n"
                "USAGE\n"
                "  " << prog << " conv -pre <scf.in> <ecutwfc|kspacing> <min> <max> <step> [outdir]\n"
                "\n"
                "ARGUMENTS\n"
                "  scf.in     Template QE SCF input (ibrav=0, K_POINTS automatic required for kspacing)\n"
                "  ecutwfc    Vary plane-wave cutoff (Ry); ecutrho scaled proportionally if present\n"
                "  kspacing   Vary k-point spacing (1/Ang) for Monkhorst-Pack mesh; requires CELL_PARAMETERS\n"
                "  min        Minimum parameter value (inclusive)\n"
                "  max        Maximum parameter value (inclusive)\n"
                "  step       Step size\n"
                "  outdir     Output directory (default: conv_ecutwfc or conv_kspacing)\n"
                "\n"
                "EXAMPLES\n"
                "  " << prog << " conv -pre si.scf.in ecutwfc 20 80 10\n"
                "  " << prog << " conv -pre si.scf.in kspacing 0.05 0.30 0.05 si_kconv\n";
        } else if (sub == "-post") {
            std::cout <<
                "DESCRIPTION\n"
                "  Scans <outdir> for subdirectories named <param>_<value>/scf.out, parses\n"
                "  total energies, computes |ΔE| in meV/atom relative to the most converged\n"
                "  (largest param) point, and writes a table + PNG convergence plot.\n"
                "\n"
                "USAGE\n"
                "  " << prog << " conv -post <outdir> <ecutwfc|kspacing> [output_prefix]\n"
                "\n"
                "ARGUMENTS\n"
                "  outdir         Directory created by conv -pre\n"
                "  ecutwfc|kspacing  Must match what was used in -pre\n"
                "  output_prefix  Prefix for .conv.txt and .conv.png (default: outdir/param)\n"
                "\n"
                "EXAMPLES\n"
                "  " << prog << " conv -post conv_ecutwfc ecutwfc\n"
                "  " << prog << " conv -post si_kconv kspacing si_kconv/kspacing\n";
        } else {
            std::cout <<
                "USAGE\n"
                "  " << prog << " conv -pre  <scf.in> <ecutwfc|kspacing> <min> <max> <step> [outdir]\n"
                "  " << prog << " conv -post <outdir> <ecutwfc|kspacing> [output_prefix]\n"
                "\n"
                "WORKFLOW\n"
                "  1. " << prog << " conv -pre si.scf.in ecutwfc 20 80 10 si_ecut\n"
                "  2. for d in si_ecut/*/; do (cd \"$d\" && pw.x < scf.in > scf.out); done\n"
                "  3. " << prog << " conv -post si_ecut ecutwfc\n"
                "\n"
                "Run '" << prog << " conv -pre --help' or '" << prog << " conv -post --help' for details.\n";
        }
    }
    // ── struct ────────────────────────────────────────────────────────────────
    else if (cmd == "struct") {
        std::cout <<
            "DESCRIPTION\n"
            "  Reads a QE pw.x SCF input file and prints a formatted structural summary:\n"
            "  lattice parameters (a, b, c, α, β, γ, V), cell vectors, and a per-atom table\n"
            "  of fractional and Cartesian coordinates. Supports CELL_PARAMETERS (ibrav=0)\n"
            "  and common cubic ibrav values (1, 2, 3) via celldm(1) / A.\n"
            "\n"
            "  Optional: estimate Warren-Cowley short-range-order (SRO) parameters\n"
            "  alpha_ij^s = 1 - P(j|i,s)/c_j for neighbor shells s.\n"
            "  If --source output is used (or --source auto on *.out), QE final coordinates\n"
            "  are parsed from the last complete CELL_PARAMETERS / ATOMIC_POSITIONS blocks.\n"
            "\n"
            "USAGE\n"
            "  " << prog << " struct -post <structure_file> [output_prefix] [--sro] [--nshells N] [--tol T] [--source input|output|auto]\n"
            "\n"
            "ARGUMENTS\n"
            "  structure_file QE pw.x SCF input, or QE output file containing final coordinates\n"
            "  output_prefix  Prefix for <prefix>.struct.txt and <prefix>.sro.txt\n"
            "                (default: stem of structure_file)\n"
            "  --sro          Enable Warren-Cowley SRO estimation\n"
            "  --nshells N    Number of neighbor shells to include (default: 2)\n"
            "  --tol T        Shell clustering tolerance in Angstrom (default: 1e-3)\n"
            "  --source ...   input | output | auto (default: auto)\n"
            "\n"
            "EXAMPLES\n"
            "  " << prog << " struct -post si.scf.in\n"
            "  " << prog << " struct -post al.scf.in al_struct\n"
            "  " << prog << " struct -post ni_co.scf.in ni_co --sro --nshells 3\n"
            "  " << prog << " struct -post ni_co.relax.out ni_co --sro --source output\n";
    }
    // ── parse ─────────────────────────────────────────────────────────────────
    else if (cmd == "parse") {
        std::cout <<
            "DESCRIPTION\n"
            "  General-purpose QE pw.x stdout parser. Extracts and reports:\n"
            "    - Total energy (Ry and eV)\n"
            "    - Fermi energy (eV)\n"
            "    - Per-atom forces and max force (Ry/au)\n"
            "    - Pressure (kbar) from the stress tensor\n"
            "    - SCF convergence status and iteration count\n"
            "    - Wall time\n"
            "  Saves a summary to <prefix>.parse.txt.\n"
            "\n"
            "USAGE\n"
            "  " << prog << " parse -post <qe.out> [output_prefix]\n"
            "\n"
            "ARGUMENTS\n"
            "  qe.out         QE pw.x stdout (the output of a pw.x run)\n"
            "  output_prefix  Prefix for <prefix>.parse.txt (default: stem of qe.out)\n"
            "\n"
            "EXAMPLES\n"
            "  " << prog << " parse -post si.scf.out\n"
            "  " << prog << " parse -post al.relax.out al_relax\n";
    }
    // ── qha ──────────────────────────────────────────────────────────────────
    else if (cmd == "qha") {
        if (sub.empty() || sub == "-pre") {
            std::cout <<
                "DESCRIPTION\n"
                "  Generate uniformly-scaled QE SCF input files for quasi-harmonic\n"
                "  approximation (QHA). Each subdirectory contains a scaled pw.x input\n"
                "  and a minimal phonopy.conf. Also creates a qha_summary.in template\n"
                "  which you fill with DFT energies after running pw.x, then pass to\n"
                "  'qha -post' to compute thermal properties.\n"
                "\n"
                "USAGE\n"
                "  " << prog << " qha -pre <scf.in> [--nvolumes N] [--range R] [--outdir D]\n"
                "\n"
                "ARGUMENTS\n"
                "  scf.in        Equilibrium QE pw.x SCF input (must have CELL_PARAMETERS angstrom)\n"
                "  --nvolumes N  Number of volume points (default: 7, minimum: 4)\n"
                "  --range R     Symmetric volume range in percent (default: 10 -> +/-5%)\n"
                "  --outdir D    Output directory (default: <stem>_qha)\n"
                "\n"
                "EXAMPLES\n"
                "  " << prog << " qha -pre si.scf.in\n"
                "  " << prog << " qha -pre si.scf.in --nvolumes 9 --range 12 --outdir si_qha\n";
        }
        if (sub.empty() || sub == "-post") {
            std::cout <<
                "DESCRIPTION\n"
                "  Compute QHA thermal properties from a set of phonopy thermal_properties.yaml\n"
                "  files and corresponding DFT static energies. Reads a summary file produced\n"
                "  by 'qha -pre' (after filling in the energy column).\n"
                "  Outputs: Birch-Murnaghan EOS parameters, V(T), G(T), B_T(T), alpha(T),\n"
                "           Cv(T), Cp(T), entropy(T), and Gruneisen parameter.\n"
                "\n"
                "USAGE\n"
                "  " << prog << " qha -post <qha_summary.in> [output_prefix]\n"
                "\n"
                "ARGUMENTS\n"
                "  qha_summary.in  File with columns: volume(Ang^3)  energy(Ry)  yaml_path\n"
                "  output_prefix   Prefix for <prefix>.qha.txt (default: stem of summary file)\n"
                "\n"
                "SUMMARY FILE FORMAT\n"
                "  # comments start with #\n"
                "  # volume(Ang^3)  energy(Ry)  thermal_properties.yaml\n"
                "  270.123  -156.7432  v01/thermal_properties.yaml\n"
                "  280.456  -157.1021  v02/thermal_properties.yaml\n"
                "\n"
                "EXAMPLES\n"
                "  " << prog << " qha -post si_qha/qha_summary.in\n"
                "  " << prog << " qha -post si_qha/qha_summary.in si_qha_results\n";
        }
    }
    // ── phonon ───────────────────────────────────────────────────────────────
    else if (cmd == "phonon") {
        if (sub.empty() || sub == "-pre") {
            std::cout <<
                "DESCRIPTION\n"
                "  Generate all QE input files needed for a DFPT phonon calculation:\n"
                "    ph.in           ph.x phonon calculation (ldisp, q-mesh)\n"
                "    q2r.in          q2r.x real-space IFC conversion\n"
                "    matdyn_dos.in   matdyn.x phonon DOS\n"
                "    matdyn_band.in  matdyn.x phonon dispersion\n"
                "\n"
                "USAGE\n"
                "  " << prog << " phonon -pre <scf.in> [--nq NQ1 NQ2 NQ3]\n"
                "                         [--nq-dos NQ1 NQ2 NQ3] [--epsil] [--asr TYPE]\n"
                "                         [outdir]\n"
                "\n"
                "ARGUMENTS\n"
                "  scf.in            pw.x SCF input (prefix, outdir, nat are read)\n"
                "  --nq NQ1 NQ2 NQ3  q-mesh for ph.x (default: 4 4 4)\n"
                "  --nq-dos N N N    q-mesh for matdyn DOS (default: 8 8 8)\n"
                "  --epsil           Include Born charges / dielectric constant (epsil=.true.)\n"
                "  --asr TYPE        Acoustic sum rule type: no/simple/crystal (default: simple)\n"
                "  outdir            Output directory (default: current directory)\n"
                "\n"
                "WORKFLOW\n"
                "  qepp phonon -pre  scf.in --nq 4 4 4 phonon_inputs/\n"
                "  mpirun ph.x    -in phonon_inputs/ph.in    > ph.out\n"
                "  q2r.x               < phonon_inputs/q2r.in    > q2r.out\n"
                "  matdyn.x            < phonon_inputs/matdyn_dos.in\n"
                "  matdyn.x            < phonon_inputs/matdyn_band.in\n"
                "  qepp phonon -post <prefix>\n"
                "\n"
                "EXAMPLES\n"
                "  " << prog << " phonon -pre si_scf.in\n"
                "  " << prog << " phonon -pre si_scf.in --nq 6 6 6 --nq-dos 12 12 12 ph_inputs/\n";
        }
        if (sub.empty() || sub == "-post") {
            std::cout <<
                "DESCRIPTION\n"
                "  Post-process matdyn.x output (from phonon -pre / DFPT workflow).\n"
                "  Reads <prefix>.phonon.dos and/or <prefix>.phonon_band.freq and\n"
                "  produces DOS plot, band structure plot, and HA thermodynamics.\n"
                "\n"
                "USAGE\n"
                "  " << prog << " phonon -post <prefix> [--dos] [--band] [--ha]\n"
                "                          [--natom N] [--tmin T] [--tmax T] [--dt T]\n"
                "                          [--labels G,X,M,G] [--qlabels <file>]\n"
                "                          [output_prefix]\n"
                "\n"
                "ARGUMENTS\n"
                "  prefix            Stem used in matdyn_dos.in / matdyn_band.in\n"
                "  --dos             Plot phonon DOS (reads <prefix>.phonon.dos)\n"
                "  --band            Plot band structure (reads <prefix>.phonon_band.freq)\n"
                "  --ha              Compute HA thermodynamics from DOS\n"
                "  --natom N         Atoms per unit cell for per-atom normalisation (default: 1)\n"
                "  --tmin/tmax/dt    Temperature range in K (defaults: 50/1000/50)\n"
                "  --labels G,X,...  Comma-separated high-symmetry point labels\n"
                "  --qlabels file    File with 'label kx ky kz' lines for band labels\n"
                "  output_prefix     Output file prefix (default: same as prefix)\n"
                "\n"
                "  Default (no --dos/--band/--ha): runs all three.\n"
                "\n"
                "EXAMPLES\n"
                "  " << prog << " phonon -post si\n"
                "  " << prog << " phonon -post si --ha --natom 2 --tmax 1200\n"
                "  " << prog << " phonon -post si --band --labels G,X,W,L,G si_bands\n";
        }
        if (sub.empty() || sub == "-dos") {
            std::cout <<
                "DESCRIPTION\n"
                "  Plot phonon density of states.  Accepts both phonopy total_dos.dat\n"
                "  and matdyn.x DOS output (format auto-detected from file header).\n"
                "  Saves <prefix>.phonon_dos.dat and <prefix>.phonon_dos.png.\n"
                "\n"
                "USAGE\n"
                "  " << prog << " phonon -dos <dos_file> [--pdos projected_dos.dat]\n"
                "                             [--labels a,b,c] [output_prefix]\n"
                "\n"
                "ARGUMENTS\n"
                "  dos_file           phonopy total_dos.dat OR matdyn.x .dos file\n"
                "  --pdos file        phonopy projected_dos.dat (phonopy workflow only)\n"
                "  --labels a,b,...   Comma-separated atom labels for PDOS legend\n"
                "  output_prefix      Output file prefix (default: stem of input)\n"
                "\n"
                "EXAMPLES\n"
                "  " << prog << " phonon -dos total_dos.dat\n"
                "  " << prog << " phonon -dos si.phonon.dos si_dos\n"
                "  " << prog << " phonon -dos total_dos.dat --pdos projected_dos.dat --labels Si,Si si_phonon\n";
        }
        if (sub.empty() || sub == "-band") {
            std::cout <<
                "DESCRIPTION\n"
                "  Plot phonon band structure.  Accepts both phonopy band.yaml and\n"
                "  matdyn.x &plot frequency output (format auto-detected).\n"
                "  Saves <prefix>.phonon_band.dat and <prefix>.phonon_band.png.\n"
                "\n"
                "USAGE\n"
                "  " << prog << " phonon -band <file> [--labels G,X,M,G]\n"
                "                               [--qlabels <file>] [output_prefix]\n"
                "\n"
                "ARGUMENTS\n"
                "  file               phonopy band.yaml OR matdyn.x .freq file\n"
                "  --labels G,X,...   High-symmetry point labels (comma-separated)\n"
                "  --qlabels file     File with 'label kx ky kz' lines (matdyn workflow)\n"
                "  output_prefix      Output file prefix (default: stem of input)\n"
                "\n"
                "EXAMPLES\n"
                "  " << prog << " phonon -band band.yaml\n"
                "  " << prog << " phonon -band si.phonon_band.freq --labels G,X,W,L,G si_bands\n";
        }
        if (sub.empty() || sub == "-ha") {
            std::cout <<
                "DESCRIPTION\n"
                "  Compute harmonic approximation (HA) thermodynamic properties from a\n"
                "  phonon DOS file.  Accepts both phonopy total_dos.dat and matdyn.x DOS\n"
                "  output (format auto-detected).\n"
                "  Integrates the phonon DOS to give: ZPE, F_vib(T), S(T), Cv(T), E_vib(T).\n"
                "  Results are reported per atom.\n"
                "\n"
                "USAGE\n"
                "  " << prog << " phonon -ha <dos_file> [--tmin T] [--tmax T] [--dt T]\n"
                "                                       [--natom N] [output_prefix]\n"
                "\n"
                "ARGUMENTS\n"
                "  dos_file       phonopy total_dos.dat OR matdyn.x .dos file\n"
                "  --tmin T       Minimum temperature in K (default: 50)\n"
                "  --tmax T       Maximum temperature in K (default: 1000)\n"
                "  --dt T         Temperature step in K (default: 50)\n"
                "  --natom N      Atoms per unit cell for per-atom normalisation (default: 1)\n"
                "  output_prefix  Output file prefix (default: stem of input)\n"
                "\n"
                "OUTPUTS\n"
                "  <prefix>.phonon_ha.txt   Table: T, F_vib, S, Cv, E_vib (per atom)\n"
                "  <prefix>.phonon_ha.png   Three-panel plot: Cv(T), S(T), F_vib(T)\n"
                "\n"
                "PHYSICAL CONVENTIONS\n"
                "  h  = 4.135667696e-3 eV/THz  (E = h*nu, cyclic THz)\n"
                "  kB = 8.617333262e-5 eV/K\n"
                "  Cv and S also reported in J/mol/K (eV/K * NA*e = 96485 J/mol/K)\n"
                "\n"
                "EXAMPLES\n"
                "  " << prog << " phonon -ha total_dos.dat --natom 2\n"
                "  " << prog << " phonon -ha si.phonon.dos --natom 2 --tmin 100 --tmax 1500 si_ha\n";
        }
    }
    // ── qha_elastic ──────────────────────────────────────────────────────────
    else if (cmd == "qha_elastic") {
        if (sub.empty() || sub == "-pre") {
            std::cout <<
                "DESCRIPTION (-pre)\n"
                "  Generate all inputs for a temperature-dependent elastic constant calculation\n"
                "  within the quasi-harmonic approximation (QHA).\n"
                "  For each of N volume-scaled cells it creates:\n"
                "    <outDir>/v01/  …  vNN/\n"
                "      <prefix>.in          volume-scaled QE SCF input\n"
                "      elastic/             strain-deformed SCF inputs (energy-strain method)\n"
                "      dfpt/                phonon inputs (ph.x, q2r.x, matdyn_dos.in)\n"
                "    qha_elastic_summary.in\n"
                "\n"
                "USAGE\n"
                "  " << prog << " qha_elastic -pre <scf.in>\n"
                "                    [--nvolumes N]   [--range R]\n"
                "                    [--ndeltas N]    [--maxdelta D]\n"
                "                    [--nq N]         [--nq-dos N]\n"
                "                    [--tr2ph X]\n"
                "                    [--outdir D]\n"
                "\n"
                "OPTIONS\n"
                "  --nvolumes N    Number of volumes (default: 7, must be >= 4)\n"
                "  --range R       Total volume range in % (default: 10 → ±5% around V₀)\n"
                "  --ndeltas N     Strain points per pattern, odd (default: 7)\n"
                "  --maxdelta D    Max strain amplitude (default: 0.04)\n"
                "  --nq N          Isotropic DFPT q-mesh for ph.x (default: 4)\n"
                "  --nq-dos N      Isotropic DOS mesh for matdyn.x (default: 16)\n"
                "  --tr2ph X       ph.x convergence threshold (default: 1e-14)\n"
                "  --outdir D      Output root directory\n"
                "\n"
                "EXAMPLES\n"
                "  " << prog << " qha_elastic -pre si_scf.in\n"
                "  " << prog << " qha_elastic -pre si_scf.in --nvolumes 9 --range 12 --nq 2 --outdir si_qha_el\n";
        }
        if (sub.empty() || sub == "-run") {
            std::cout <<
                "DESCRIPTION (-run)\n"
                "  Run the generated QHA elastic workflow across all v*/ directories.\n"
                "  For each volume it executes, if needed:\n"
                "    1. top-level SCF (qe.out)\n"
                "    2. all elastic strain SCFs\n"
                "    3. ph.x, q2r.x, matdyn.x\n"
                "  Existing stages containing JOB DONE are skipped automatically.\n"
                "  If omitted, <dataset_dir> defaults to the current directory.\n"
                "\n"
                "USAGE\n"
                "  " << prog << " qha_elastic -run <dataset_dir>\n"
                "  " << prog << " qha_elastic -run\n"
                "                     [--np N] [--ni N] [--nk N] [--nb N] [--nt N] [--nd N]\n"
                "                     [--exclude v04,v07]\n"
                "\n"
                "OPTIONS\n"
                "  --np N          MPI ranks passed to mpirun (default: 1)\n"
                "  --ni N          QE image groups   (-ni)\n"
                "  --nk N          QE k-point pools  (-nk)\n"
                "  --nb N          QE band groups    (-nb)\n"
                "  --nt N          QE task groups    (-nt)\n"
                "  --nd N          QE diagonalization groups (-nd)\n"
                "  --exclude LIST  Comma-separated volume directories to skip\n"
                "\n"
                "EXAMPLES\n"
                "  " << prog << " qha_elastic -run si_qha_el --np 20 --nk 4\n"
                "  " << prog << " qha_elastic -run --np 20 --nk 4 --nb 2 --nd 5 --exclude v04\n";
        }
        if (sub.empty() || sub == "-post") {
            std::cout <<
                "DESCRIPTION (-post)\n"
                "  Read a qha_elastic_summary.in, run elastic post-processing for each volume,\n"
                "  read phonon DOS files, and compute temperature-dependent C_ij(T) tensors.\n"
                "  If the energy column is not numeric, qepp automatically reads the static\n"
                "  energy from qe.out (or <scf_stem>.out) in the corresponding volume directory.\n"
                "\n"
                "  Two contributions are computed and summed:\n"
                "    1. Quasi-static C_ij^{QS}(T): static elastic tensor interpolated to V(T)\n"
                "    2. Phonon bulk correction B^{ph}(T) = V·d²F_vib/dV² added to normal\n"
                "       components; leaves shear constants unchanged.\n"
                "\n"
                "USAGE\n"
                "  " << prog << " qha_elastic -post <qha_elastic_summary.in|dataset_dir>\n"
                "  " << prog << " qha_elastic -post\n"
                "                     [output_prefix]\n"
                "                     [--tmin T] [--tmax T] [--dt T] [--exclude v04]\n"
                "\n"
                "OPTIONS\n"
                "  --tmin T    Minimum temperature in K (default: 0)\n"
                "  --tmax T    Maximum temperature in K (default: 1500)\n"
                "  --dt T      Temperature step in K    (default: 10)\n"
                "  --exclude   Comma-separated volume directories to ignore\n"
                "\n"
                "OUTPUTS\n"
                "  <prefix>.qha_elastic.txt  Full C_ij(T) table + VRH moduli vs temperature\n"
                "\n"
                "EXAMPLES\n"
                "  " << prog << " qha_elastic -post si_qha_el\n"
                "  " << prog << " qha_elastic -post --exclude v04 --tmin 0 --tmax 1000 --dt 50\n";
        }
    }
    else {
        std::cerr << "Unknown command '" << cmd << "'. Run '" << prog << " help' for the list.\n";
    }
}
